apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-${APP_NAME}
data:
  jdbc.properties: |
    mysql.addr=127.0.0.1
    mysql.user=mysql
    mysql.port=3306
    mysql.password=password
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${APP_NAME}
  labels:
    app: svc-${APP_NAME}
spec:
  selector:
    app: deploy-${APP_NAME}
  ports:
  - protocol: TCP
    name: http
    nodePort: ${SERVICE_PORT}
    port: ${SERVICE_PORT}
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deploy-${APP_NAME}
  labels:
    app: deploy-${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-${APP_NAME}
  template:
    metadata:
      labels:
        app: deploy-${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: 192.168.0.150:5000/admin/${APP_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "512m"
            memory: "512Mi"
        env:
        - name: aliyun_logs_nginx
          value: stdout
        - name: aliyun_logs_nginx_tags
          value: "index=nginx,topic=nginx,stage=test"
        - name: aliyun_logs_nginx_format
          value: json 
        volumeMounts:
          - name: config-volume
            mountPath: /etc/apps/config
      volumes:
        - name: config-volume
          configMap:
            name: cfg-${APP_NAME}
