apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-${APP_NAME}
data:
  application.properties: |
    spring.application.name=${APP_NAME}
    server.port=${SERVICE_PORT}
    eureka.client.service-url.default-zone=${EUREKA_SERVER_URL}
  jdbc.properties: |
    mysql.addr=127.0.0.1
    mysql.user=mysql
    mysql.port=3306
    mysql.password=password
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${APP_NAME}
  labels:
    app: svc-${APP_NAME}
spec:
  selector:
    app: deploy-${APP_NAME}
  ports:
  - protocol: TCP
    name: http
    port: ${SERVICE_PORT}
    targetPort: ${SERVICE_PORT}
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deploy-${APP_NAME}
  labels:
    app: deploy-${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-${APP_NAME}
  template:
    metadata:
      labels:
        app: deploy-${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: registry-vpc.cn-beijing.aliyuncs.com/ier/${APP_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: ${SERVICE_PORT}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/apps/config
      volumes:
        - name: config-volume
          configMap:
            name: cfg-${APP_NAME}
